name: egon_bot
description: Personal assistant Discord bot powered by nyxx and a local Ollama instance.
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dotenv: ^4.2.0
  nyxx: ^6.9.0
